### PR TITLE
Configuration for Travis CI

### PR DESCRIPTION
**Pull request by chatchavan**
**DO NOT MERGE THIS COMMIT: Specific modifications are needed to make it works on the transparentstats/master**

From: https://github.com/transparentstats/guidelines/issues/16

The following is the configuration for Travis CI. It is configured specifically for [my fork](https://github.com/chatchavan/guidelines/tree/effect-size). You can find the output compiled by Travis [here](https://chatchavan.github.io/guidelines/).

Decision made:

- Required libraries are listed in `.travis.yml` instead of `DESCRIPTION` because Travis doesn't correctly install github-based packages when I specified them in the `DESCRIPTION` file.
- The compiled result will be put in the `gh-pages` branch with the `Robot<robot@transparentstatistics.org>` user name

TODOs:
- Wiki
   - [ ] Add required packages to `.travis.yml`.

I'll wait for the following before configure the Travis CI for the transparentstats/master branch:

- [ ] Two approvals
- [ ] Effect size is merged back to the master

### CODE REVIEW

**Comment by mjskay** [comment]
Do you want me to set up robot@transparentstatistics.org to forward to you?

**Comment by chatchavan** [comment]
No need to. It’s only for the commit log on GitHub.

— Chat

**Comment by steveharoz** [comment]
I don't understand what this does. As long as everything can be compiled via RStudio+libraries without external software.

**Comment by chatchavan** [comment]
This detects the latest commit on GitHub and compile it to a readable HTML automatically.

Cheers,
Chat

**Comment by shionguha** [comment]
Agreed with @steveharoz . I'm also not sure what this does but happy to learn.

**Comment by mjskay** [comment]
@chatchavan is this stale now? I am doing some cleanup and wanted to check if we can close this.

**Comment by chatchavan** [comment]
This is stale. The current version uses `DESCRIPTION` file for package requirements and installation.

Effect size branch is merged.

**Comment by mjskay** [comment]
Thanks!

**Pull request closed without merging**
