### PR TITLE
Ported to bookdown format

### PR DESCRIPTION
**Pull request by chatchavan**
See also: https://github.com/transparentstats/guidelines/issues/16

Please focus this review on the usability/readability of the bookdown format.

**Decision made:**

- Don't prefix file names with number. Instead, determine chapter order in `_book.yml`
   - *Reason:* Avoid having to change between-file links when the chapter order changes.

**TODOs:**

- [ ] Automatic build from Travis (I'm currently looking into this.)
- [ ] Add to wiki:
    - [ ] Modification required to `_book.yml` when a new file is added.
    - [ ] Use "Build book" on the "Build pane" to compile instead of the "Knit" button
    - [ ] Use `knitr::includegraphics()` for images

**Possible concern:**

- After moving to bookdown, I couldn't figure out how to configure RStudio to compile individual file anymore. (Compiling individual file might be useful for quick turnaround for commenting/debugging in-progress FAQ or exemplars.)

### CODE REVIEW

**Comment by steveharoz** [comment]
Cool! Could you build this and post it, so I can have a look?

**Comment by chatchavan** [comment]
Here you go: https://chatchavan.github.io/guidelines/

**Comment by mjskay** [comment]
Also to add to TODOs: update wiki to state that {#id} format is the way to make heading ids in bookdown, but that <a id></a> is needed for the wiki.

**Comment by chatchavan** [comment]
@mjskay Page-level vs. book-level reference list: I enabled page-level reference list (`split_bib: yes`) to make it faster for readers to look up the reference by clicking the link. (No delay in loading a new page with a potentially very long list of reference.)

As for the book-level reference list, I haven't found a mean to turn it off. At the moment I believe that it doesn't do any harm, so I'll leave it as is.

**Comment by chatchavan** [comment]
I've put TODOS in https://github.com/transparentstats/guidelines/issues/16 as well.

**Pull request merged**
