### PR TITLE
Moved content to subdirectory

### PR DESCRIPTION
**Pull request by steveharoz**
This addresses issue #49

**Note: I couldn't get the rstan package to install, so I temporarily removed the appendix from the list** 

Due to an imperfect workaround, the labels for all code chunks need to be unique across all files (blank works too).

~~I also removed any empty Rmd files. We can add them back once we have content.~~

### CODE REVIEW

**Comment by mjskay** [comment]
Thanks!

> Note: I couldn't get the rstan package to install, so I temporarily removed the appendix from the list

Yeah, it can be a pain compared to other packages :/. Did you try the instructions here? https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started

Just installing with `install.packages` tends not to work in my experience. I do wish they would fix that.

That said, I would rather have the appendix set to compile in the version in the repo, since it should be visible on the website (which will be done automatically from the repo contents).

> I also removed any empty Rmd files. We can add them back once we have content.

I think that having the stubs gives us standard ids to link to, so that once those files have content a bunch of links will already work (I believe there are already references to the inferential one, for example). Does leaving them around hurt anything?

**Comment by steveharoz** [comment]
I have no idea what's up with RStan. I have Rtools installed, but don't know what that path thing is. 

Are you sure it's a good idea to have such a massive (RTools is > 1GB) and complex setup requirement to use or contribute to this guide? Is there any alternative to that package on CRAN or github?

**Comment by steveharoz** [comment]
I can't confirm that any edits I made compile while the appendix is included

**Comment by chatchavan** [comment]
I agree with @steveharoz that it's quite demanding for people who wish to contribute to non-Bayesian part to have to go through the installation process. However, I also agree with @mjskay point that the appendix should be an integral part. Moreover, further Bayesian content will require these libraries anyway. (To my knowledge RStan is the *de facto* software package for Bayesian analysis.)

I'd propose to make an instruction for contributors on how to remove parts of the book by removing respective lines in `_bookdown.yml`. This will allow them to exclude all but the part that they are focusing on, thus making the Build process faster as well.

**Comment by steveharoz** [comment]
I uninstalled and reinstalled RTools, and RStan finally installed.

There are a lot of libraries required exclusively for the appendix. I added a script at the top which installs everything because the cycle of build->error->install->repeat gets tiresome after a few minutes.
 
But now, I get an error when I build:
```{r}
m_log_bayes <- brm(brmsformula(
    completion_time_ms ~ group,
    sigma ~ group    # allow variance to be different in each group
  ), data = data, family = lognormal)
```
**Error:**
```
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! c:/Rtools/mingw_64/bin/g++: not found
```

@mjskay: any idea what's going wrong?

**Comment by mjskay** [comment]
Did you go through all the steps on https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Windows ? If not, I would remove the rstan package, close all R sessions, and then follow the steps on that page. Does the last step on that page pass? (the check for compiling a simple c++ program through R)?

The problem with auto-installing rstan with install.packages() is that it will end up with broken installations from people not following the instructions on the rstan wiki. I think we might need to have a "getting started" page in the wiki (or maybe the README) that people can read that lists all packages used by every doc, with step-by-step instructions to get set up. So it would have them install rstan using the rstan wiki instructions, then run the auto-install script you have provided to install everything else.

**Pull request merged**
